### Base URL
@PersonService_HostAddress = https://localhost:7252
@ContentType = application/json

### Get all persons
GET {{PersonService_HostAddress}}/api/persons?page=1&page-size=5
Accept: {{ContentType}}

### Get person by Id
GET {{PersonService_HostAddress}}/api/persons/2a407bc7-5a8c-493e-ae66-6e56fe7e4271
Accept: {{ContentType}}

### Create person
POST {{PersonService_HostAddress}}/api/persons
Accept: {{ContentType}}
Content-Type: {{ContentType}}

{
    "name": "Camila Cristina dos Santos",
    "birthDate": "2007-07-13T21:44:44.2Z",
    "cpfNumber": "74778392049",
    "cpfRegistrationDate": "2007-11-01T21:44:44.2Z",
    "rgNumber": "282759603",
    "rgIssuingAuthority": "SSP_MA"
}

### Update person
PUT {{PersonService_HostAddress}}/api/persons/a5d44af3-69d3-4604-b2f5-64073afe71f7
Accept: {{ContentType}}
Content-Type: {{ContentType}}

{
  "name": "Maria Silva"
}

### Delete person
DELETE {{PersonService_HostAddress}}/api/persons/2a407bc7-5a8c-493e-ae66-6e56fe7e4271
Accept: {{ContentType}}
